import { Quiz, Question, Answer, User } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    email: 'admin@example.com',
    name: 'Admin User',
    avatar: undefined,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'user-2',
    email: 'teacher@example.com',
    name: 'John Teacher',
    avatar: undefined,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
];

export const MOCK_QUIZZES: Quiz[] = [
  {
    id: 1,
    userId: 'user-1',
    title: 'Geometriya Asoslari',
    description: 'Geometriyaning asosiy tushunchalari va teoremalari',
    isPublic: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 2,
    userId: 'user-2',
    title: 'JavaScript Basics',
    description: 'Learn the fundamentals of JavaScript programming',
    isPublic: true,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: 3,
    userId: 'user-1',
    title: 'Ingliz Tili Grammatikasi',
    description: 'English grammar rules and exercises',
    isPublic: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 1,
    quizId: 1,
    questionText: 'Uchburchakning burchaklarining yig\'indisi nechaga teng?',
    questionType: 'multiple_choice',
    timeLimit: 30,
    points: 100,
    orderIndex: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    quizId: 1,
    questionText: 'Kvadratning barcha tomonlari tenmi?',
    questionType: 'true_false',
    timeLimit: 20,
    points: 50,
    orderIndex: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    quizId: 2,
    questionText: 'JavaScript eng ko\'p qayerda ishlatiladi?',
    questionType: 'multiple_choice',
    timeLimit: 30,
    points: 100,
    orderIndex: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const MOCK_ANSWERS: Answer[] = [
  // Quiz 1, Question 1
  {
    id: 1,
    questionId: 1,
    answerText: '90 daraja',
    isCorrect: false,
    orderIndex: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    questionId: 1,
    answerText: '180 daraja',
    isCorrect: true,
    orderIndex: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    questionId: 1,
    answerText: '270 daraja',
    isCorrect: false,
    orderIndex: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    questionId: 1,
    answerText: '360 daraja',
    isCorrect: false,
    orderIndex: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Quiz 1, Question 2
  {
    id: 5,
    questionId: 2,
    answerText: 'Ha (True)',
    isCorrect: true,
    orderIndex: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    questionId: 2,
    answerText: 'Yo\'q (False)',
    isCorrect: false,
    orderIndex: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Quiz 2, Question 1
  {
    id: 7,
    questionId: 3,
    answerText: 'Backend serverida',
    isCorrect: false,
    orderIndex: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 8,
    questionId: 3,
    answerText: 'Veb brauzerida',
    isCorrect: true,
    orderIndex: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9,
    questionId: 3,
    answerText: 'Mobil applikatsiyalarda',
    isCorrect: false,
    orderIndex: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 10,
    questionId: 3,
    answerText: 'Desktop applikatsiyalarda',
    isCorrect: false,
    orderIndex: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
